<?php

function cipher_menu() {
    $items['cipher'] = array(
        'title' => 'Sensei Cyber Cipher',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['cipher_result'] = array(
        'title' => 'Your Ciphered Phrase:',
        'page callback' => 'cipher_result',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['phrase'] = array(
        '#title' => 'Input Phrase:',
        '#type' => 'textfield',
        '#description' => t('Enter a phrase you wish to cipher and encrypt'),
        '#required' => TRUE,
    );
    $form['shift_value'] = array(
        '#title' => 'Shift Value:',
        '#type' => 'textfield',
        '#description' => t('Enter a number between 1 and 25 that you would like to shift/cipher encrypt each letter in your phrase'),
        '#element_validate' => array('element_validate_number', 'element_validate_integer_positive', 'element_validate_range'),
        '#required' => TRUE,
    );
    $form['direction'] = array(
        '#title' => 'Direction of Shift:',
        '#type' => 'textfield',
        '#description' => t('Enter either "right" or "left" to tell the cipher which way to encrypt your phrase'),
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Cipher Dat Shiz!',
    );
    return $form;
}

function element_validate_direction($element) {
    if ($element['#value'] != 'left' && $element['#value'] != 'right') {
        form_error($element, t('Warning: You may only enter "left" or "right" for this input field!'));
    }
}

function element_validate_range($element) {
    if ($element['#value'] < 1 || $element['#value'] > 25) {
        form_error($element, t('Warning: You must enter a number within the valid range specified!!'));
    }
}

function cipher_form_submit($form, &$form_state) {
    $input_phrase = strtolower($form_state['values']['phrase']);
    $input_array = explode(" ", $input_phrase);
    $punctuation = array("+",",",".","-","'","\"","&","!","?",":",";","#","~","=","/","$","£","^","(",")","_","<",">");
    $alphabet = array('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z');

    foreach($input_array as $index => $word)

    $output_array = array();

}
